# Use official PHP image with Apache
FROM php:8.1-apache

# Install system dependencies and PHP extensions
RUN apt-get update -y && \
    apt-get install -y libmcrypt-dev git openssl zip unzip && \
    docker-php-ext-install pdo pdo_mysql mysqli && \
    a2enmod rewrite

# Set working directory inside the container
WORKDIR /var/www/html

# Copy application files into the container
COPY . /var/www/html

# Set proper permissions for the application
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html


# Expose port 80 for the application
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
